// <auto-generated />
using System;
using CarFitProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarFitProject.Migrations
{
    [DbContext(typeof(CarFitDbContext))]
    [Migration("20260529230617_Phase2a_QuestionnaireFields")]
    partial class Phase2a_QuestionnaireFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarFitProject.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("body_type");

                    b.Property<string>("EngineSize")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("engine_size");

                    b.Property<string>("ExteriorColor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("exterior_color");

                    b.Property<string>("ExteriorOptions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("exterior_options");

                    b.Property<string>("FuelEfficiency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fuel_efficiency");

                    b.Property<string>("FuelType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("fuel_type");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("images");

                    b.Property<string>("InteriorColor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("interior_color");

                    b.Property<string>("InteriorOptions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("interior_options");

                    b.Property<string>("Kilometers")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("kilometers");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<string>("RegionalSpecs")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("regional_specs");

                    b.Property<int?>("ScrapedId")
                        .HasColumnType("int")
                        .HasColumnName("scraped_id");

                    b.Property<int?>("Seats")
                        .HasColumnType("int")
                        .HasColumnName("seats");

                    b.Property<string>("TechnologyOptions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("technology_options");

                    b.Property<string>("Transmission")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("transmission");

                    b.Property<string>("Trim")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trim");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("PK__Cars__3213E83F43C12A3A");

                    b.HasIndex(new[] { "Transmission", "BodyType", "Year" }, "IX_Cars_Matching");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarFitProject.Models.CarListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("available");

                    b.Property<int?>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    b.Property<bool?>("InstallmentOption")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("installment_option");

                    b.Property<decimal?>("ListingPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("listing_price");

                    b.Property<string>("PaymentMethodAllowed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_method_allowed");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("seller_id");

                    b.HasKey("Id")
                        .HasName("PK__CarListi__3213E83F8D2FA73D");

                    b.HasIndex("CarId");

                    b.HasIndex("SellerId");

                    b.HasIndex(new[] { "Available" }, "IX_CarListings_Availability");

                    b.ToTable("CarListings");
                });

            modelBuilder.Entity("CarFitProject.Models.InspectionBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PreferredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("InspectionBookings");
                });

            modelBuilder.Entity("CarFitProject.Models.InspectionReport", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    b.Property<string>("BodyCondition")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("body_condition");

                    b.Property<decimal?>("CalculatedTrustScore")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("calculated_trust_score");

                    b.Property<bool?>("CarseerAttached")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("carseer_attached");

                    b.Property<string>("CenterName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("center_name");

                    b.Property<string>("Chassis1Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("chassis_1_status");

                    b.Property<string>("Chassis2Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("chassis_2_status");

                    b.Property<string>("Chassis3Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("chassis_3_status");

                    b.Property<string>("Chassis4Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("chassis_4_status");

                    b.Property<string>("DescriptionScore")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description_score");

                    b.Property<int?>("EngineHealthPercent")
                        .HasColumnType("int")
                        .HasColumnName("engine_health_percent");

                    b.Property<bool?>("EngineSmoke")
                        .HasColumnType("bit")
                        .HasColumnName("engine_smoke");

                    b.Property<string>("GearboxStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("gearbox_status");

                    b.Property<DateOnly?>("InspectionDate")
                        .HasColumnType("date")
                        .HasColumnName("inspection_date");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("overall_score");

                    b.Property<string>("PaintFillerStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paint_filler_status");

                    b.Property<string>("PaintStatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paint_status");

                    b.Property<string>("RoofCondition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("roof_condition");

                    b.HasKey("CarId")
                        .HasName("PK__Inspecti__4C9A0DB3B4E9E2BC");

                    b.ToTable("InspectionReports");
                });

            modelBuilder.Entity("CarFitProject.Models.InspectionTermsGlossary", b =>
                {
                    b.Property<string>("Term")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("term");

                    b.Property<string>("ExplanationAr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("explanation_ar");

                    b.Property<string>("ExplanationEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("explanation_en");

                    b.Property<string>("SeverityLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("severity_level");

                    b.HasKey("Term")
                        .HasName("PK__Inspecti__E0F9670E11FE1C38");

                    b.ToTable("InspectionTermsGlossary", (string)null);
                });

            modelBuilder.Entity("CarFitProject.Models.RecommendationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RecommendedCarIds")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recommended_car_ids");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("score");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Recommen__3213E83F3C2D9495");

                    b.HasIndex(new[] { "UserId" }, "IX_RecommendationLog_user_id");

                    b.ToTable("RecommendationLog", (string)null);
                });

            modelBuilder.Entity("CarFitProject.Models.SavedResult", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<int>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    b.Property<DateTime?>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("saved_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "CarId")
                        .HasName("PK__SavedRes__9D7797D4910E870F");

                    b.HasIndex("CarId");

                    b.ToTable("SavedResults");
                });

            modelBuilder.Entity("CarFitProject.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("identity_user_id");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approved");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("neighborhood");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Tier")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tier");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK__Sellers__3213E83F4F76A86D");

                    b.HasIndex(new[] { "IdentityUserId" }, "IX_Sellers_IdentityUserId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("CarFitProject.Models.UserProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<decimal>("BudgetMax")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("budget_max");

                    b.Property<decimal?>("BudgetMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("budget_min");

                    b.Property<string>("ConditionPref")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("condition_pref");

                    b.Property<bool?>("HasKids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("has_kids");

                    b.Property<int?>("InstallmentMonths")
                        .HasColumnType("int")
                        .HasColumnName("installment_months");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("KidsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("kids_count");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("marital_status");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("My Fit Profile")
                        .HasColumnName("profile_name");

                    b.Property<string>("Purpose")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("purpose");

                    b.Property<string>("SizePref")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("size_pref");

                    b.Property<string>("TransmissionPref")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("transmission_pref");

                    b.Property<string>("TripType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trip_type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("ProfileId")
                        .HasName("PK__UserProf__AEBB701F5EA739D8");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("CarFitProject.Models.VwAvailableCarDetail", b =>
                {
                    b.Property<string>("BodyCondition")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("body_condition");

                    b.Property<string>("BodyType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("body_type");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("DescriptionScore")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description_score");

                    b.Property<string>("EngineSize")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("engine_size");

                    b.Property<string>("ExteriorColor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("exterior_color");

                    b.Property<string>("ExteriorOptions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("exterior_options");

                    b.Property<string>("FuelType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("fuel_type");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("images");

                    b.Property<string>("InteriorColor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("interior_color");

                    b.Property<string>("InteriorOptions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("interior_options");

                    b.Property<string>("Kilometers")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("kilometers");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ListingPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("listing_price");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("neighborhood");

                    b.Property<string>("PaintStatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paint_status");

                    b.Property<string>("PaymentMethodAllowed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_method_allowed");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<string>("RegionalSpecs")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("regional_specs");

                    b.Property<int?>("ScrapedId")
                        .HasColumnType("int")
                        .HasColumnName("scraped_id");

                    b.Property<int?>("Seats")
                        .HasColumnType("int")
                        .HasColumnName("seats");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TechnologyOptions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("technology_options");

                    b.Property<string>("Transmission")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("transmission");

                    b.Property<string>("Trim")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trim");

                    b.Property<decimal>("TrustScore")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.ToTable((string)null);

                    b.ToView("vw_AvailableCarDetails", (string)null);
                });

            modelBuilder.Entity("CarFitProject.ViewModel.RecommendedCarViewModel", b =>
                {
                    b.Property<string>("BodyCondition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_condition");

                    b.Property<int>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("DescriptionScore")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_score");

                    b.Property<int>("DynamicMatchScore")
                        .HasColumnType("int")
                        .HasColumnName("DynamicMatchScore");

                    b.Property<decimal>("ListingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("listing_price");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("model");

                    b.Property<decimal>("TrustScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("trust_score");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.ToTable("RecommendedCarMatches");
                });

            modelBuilder.Entity("CarFitProject.Models.CarListing", b =>
                {
                    b.HasOne("CarFitProject.Models.Car", "Car")
                        .WithMany("CarListings")
                        .HasForeignKey("CarId")
                        .HasConstraintName("FK__CarListin__car_i__44FF419A");

                    b.HasOne("CarFitProject.Models.Seller", "Seller")
                        .WithMany("CarListings")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK__CarListin__selle__45F365D3");

                    b.Navigation("Car");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("CarFitProject.Models.InspectionReport", b =>
                {
                    b.HasOne("CarFitProject.Models.Car", "Car")
                        .WithOne("InspectionReport")
                        .HasForeignKey("CarFitProject.Models.InspectionReport", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Inspectio__car_i__49C3F6B7");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarFitProject.Models.SavedResult", b =>
                {
                    b.HasOne("CarFitProject.Models.Car", "Car")
                        .WithMany("SavedResults")
                        .HasForeignKey("CarId")
                        .IsRequired()
                        .HasConstraintName("FK__SavedResu__car_i__5070F446");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarFitProject.Models.Car", b =>
                {
                    b.Navigation("CarListings");

                    b.Navigation("InspectionReport");

                    b.Navigation("SavedResults");
                });

            modelBuilder.Entity("CarFitProject.Models.Seller", b =>
                {
                    b.Navigation("CarListings");
                });
#pragma warning restore 612, 618
        }
    }
}
